//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string gmail { get; set; }
        public string HoTen { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsAdmin { get; set; }
    }
}
